---
name: test latest image

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:

  test_latest_image:

    strategy:
      matrix:
        dataset: ['1', '2']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tree

    - name: Clone repo
      uses: actions/checkout@v3

    - name: pull docker image
      run: docker pull bids/afni_proc:latest

    - name: print version
      run: |
        docker run -t --rm --read-only \
          -v /tmp:/tmp \
          -v /var/tmp:/var/tmp \
              bids/afni_proc:latest --version
        docker run -t --rm --read-only \
          -v /tmp:/tmp \
          -v /var/tmp:/var/tmp \
              bids/afni_proc:latest --help

    - name: get data
      run: |
        wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
        bash get_data_from_osf.sh ds114_test${{ matrix.dataset }}

    - name: prepare output dir
      run: mkdir -p ${HOME}/outputs${{ matrix.dataset }}

    - name: participant level tests for single session dataset
      run: |
        docker run -ti --rm --read-only \
          -v ${HOME}/data/ds114_test1:/bids_dataset \
          -v ${HOME}/outputs${{ matrix.dataset }}:/outputs \
          -v /tmp:/tmp \
          -v /var/tmp:/var/tmp \
            bids/afni_proc \
              /bids_dataset /outputs participant \
              --participant_label 01 \
              --afni_proc \
                '-subj_id {subj_id} \
                -script proc.bids -scr_overwrite -out_dir {out_dir} \
                -blocks tshift volreg blur scale \
                -copy_anat {anat_path} -tcat_remove_first_trs 0 -dsets {epi_paths} \
                -volreg_align_to MIN_OUTLIER -blur_size 4.0 -bash'

    - name: check output
      run: tree ${HOME}/outputs${{ matrix.dataset }}
